/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.nathanmkaya.app

import dev.nathanmkaya.library.Library

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    println(Library().someLibraryMethod())
}
